-- WMS_ServiceUser schema (SQL Server)
CREATE TABLE "User" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "email" VARCHAR(100) NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "phone" VARCHAR(15),
  "provider" VARCHAR(255),
  "asRole" VARCHAR(50),
  "isActive" BIT DEFAULT 1,
  "nrp" VARCHAR(50),
  "password" VARCHAR(200),
  "createdBy" VARCHAR(100),
  "updatedBy" VARCHAR(100),
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "updatedAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "deletedAt" DATETIMEOFFSET,
  "deletedBy" VARCHAR(100),
  "token" VARCHAR(200)
);

CREATE TABLE "Role" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "name" VARCHAR(50) NOT NULL,
  "description" VARCHAR(100),
  "createdBy" VARCHAR(100) NOT NULL,
  "updatedBy" VARCHAR(100),
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "updatedAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "deletedAt" DATETIMEOFFSET,
  "deletedBy" VARCHAR(100)
);

CREATE TABLE "UserRole" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "userId" UNIQUEIDENTIFIER NOT NULL REFERENCES "User"("id"),
  "roleId" UNIQUEIDENTIFIER NOT NULL REFERENCES "Role"("id"),
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "createdBy" UNIQUEIDENTIFIER NOT NULL,
  "deletedAt" DATETIMEOFFSET,
  "deletedBy" UNIQUEIDENTIFIER
);

CREATE TABLE "Menu" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "parentId" UNIQUEIDENTIFIER REFERENCES "Menu"("id"),
  "level" INT NOT NULL,
  "menu" VARCHAR(50) NOT NULL,
  "url" VARCHAR(50),
  "icon" VARCHAR(50),
  "order" INT NOT NULL,
  "isTab" BIT DEFAULT 0,
  "menuCode" VARCHAR(50),
  "createdBy" VARCHAR(50),
  "updatedBy" VARCHAR(50),
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "updatedAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "deletedAt" DATETIMEOFFSET,
  "deletedBy" VARCHAR(50)
);

CREATE TABLE "Uam" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "roleId" UNIQUEIDENTIFIER NOT NULL REFERENCES "Role"("id"),
  "menuId" UNIQUEIDENTIFIER NOT NULL REFERENCES "Menu"("id"),
  "canCreate" BIT NOT NULL,
  "canRead" BIT NOT NULL,
  "canUpdate" BIT NOT NULL,
  "canDelete" BIT NOT NULL,
  "canEtc" BIT NOT NULL,
  "createdBy" VARCHAR(100) NOT NULL,
  "updatedBy" VARCHAR(100),
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "updatedAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "deletedAt" DATETIMEOFFSET,
  "deletedBy" VARCHAR(100)
);

CREATE TABLE "LoginAttempt" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "email" VARCHAR(100) NOT NULL,
  "attemptCount" INT NOT NULL DEFAULT 0,
  "banExpiresAt" DATETIMEOFFSET,
  "userId" UNIQUEIDENTIFIER REFERENCES "User"("id"),
  "createdBy" UNIQUEIDENTIFIER NOT NULL REFERENCES "User"("id"),
  "updatedBy" UNIQUEIDENTIFIER NOT NULL REFERENCES "User"("id"),
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "updatedAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE "LoginHistory" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "email" VARCHAR(100) NOT NULL,
  "asRole" VARCHAR(50) NOT NULL,
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  "createdBy" VARCHAR(100),
  "userId" UNIQUEIDENTIFIER NOT NULL
);

CREATE TABLE "UserRoleBranch" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "userRoleId" UNIQUEIDENTIFIER NOT NULL REFERENCES "UserRole"("id"),
  "branchId" VARCHAR(15) NOT NULL,
  "createdAt" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE "UserLoginActivity" (
  "id" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "userId" UNIQUEIDENTIFIER,
  "platform" VARCHAR(255),
  "ipAddress" VARCHAR(40),
  "channel" VARCHAR(10),
  "createdAt" DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
  "createdBy" UNIQUEIDENTIFIER,
  "name" VARCHAR(255),
  "email" VARCHAR(255)
);

CREATE TABLE "Customer" (
  "ID" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "Code" VARCHAR(50),
  "Name" VARCHAR(75),
  "Address" VARCHAR(200),
  "Phone" VARCHAR(50),
  "CreatedAt" DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
  "CreatedBy" VARCHAR(100),
  "UpdatedAt" DATETIMEOFFSET,
  "UpdatedBy" VARCHAR(100),
  "DeletedAt" DATETIMEOFFSET,
  "DeletedBy" VARCHAR(100)
);

CREATE TABLE "UserRoleWarehouse" (
  "ID" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "UserRoleId" UNIQUEIDENTIFIER REFERENCES "UserRole"("id"),
  "WarehouseId" UNIQUEIDENTIFIER,
  "CreatedAt" DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
  "CreatedBy" VARCHAR(100),
  "UpdatedAt" DATETIMEOFFSET,
  "UpdatedBy" VARCHAR(100),
  "DeletedAt" DATETIMEOFFSET,
  "DeletedBy" VARCHAR(100)
);

CREATE TABLE "Warehouse" (
  "ID" UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  "CustomerId" UNIQUEIDENTIFIER REFERENCES "Customer"("ID"),
  "Code" VARCHAR(50),
  "Name" VARCHAR(75),
  "Address" VARCHAR(200),
  "Phone" VARCHAR(50),
  "CreatedAt" DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
  "CreatedBy" VARCHAR(100),
  "UpdatedAt" DATETIMEOFFSET,
  "UpdatedBy" VARCHAR(100),
  "DeletedAt" DATETIMEOFFSET,
  "DeletedBy" VARCHAR(100)
);

ALTER TABLE "UserRoleWarehouse"
  ADD CONSTRAINT "UserRoleWarehouse_WarehouseId_fkey"
  FOREIGN KEY ("WarehouseId") REFERENCES "Warehouse"("ID");

CREATE INDEX idx_user_email ON "User"("email");
CREATE INDEX idx_user_deleted ON "User"("deletedAt");
CREATE INDEX idx_userrole_user ON "UserRole"("userId");
CREATE INDEX idx_uam_role ON "Uam"("roleId");
CREATE INDEX idx_uam_menu ON "Uam"("menuId");
